export const ptBR: Record<string, string> = {
  Iraq: "Iraque",
  Turkey: "Turquia",
  Switzerland: "Suíça",
  "Congo DR": "RD Congo",
  "New Zealand": "Nova Zelândia",
  Ecuador: "Equador",
  Uruguay: "Uruguai",
  Norway: "Noruega",
  Sweden: "Suécia",
  Scotland: "Escócia",
  Qatar: "Catar",
  Netherlands: "Países Baixos",
  Paraguay: "Paraguai",
  Jordan: "Jordânia",
  Brazil: "Brasil",
  Austria: "Áustria",
  Australia: "Austrália",
  Germany: "Alemanha",
  Canada: "Canadá",
  Uzbekistan: "Uzbequistão",
  Portugal: "Portugal",
  "South Korea": "Coreia do Sul",
  Colombia: "Colômbia",
  Panama: "Panamá",
  "Saudi Arabia": "Arábia Saudita",
  Argentina: "Argentina",
  Spain: "Espanha",
  Croatia: "Croácia",
  "Cape Verde Islands": "Ilhas de Cabo Verde",
  Tunisia: "Tunísia",
  England: "Inglaterra",
  Egypt: "Egito",
  Morocco: "Marrocos",
  Iran: "Irã",
  Belgium: "Bélgica",
  Algeria: "Argélia",
  "Bosnia-Herzegovina": "Bósnia e Herzegovina",
  France: "França",
  "South Africa": "África do Sul",
  Mexico: "México",
  Curaçao: "Curaçao",
  Senegal: "Senegal",
  Ghana: "Gana",
  Japan: "Japão",
  "Ivory Coast": "Costa do Marfim",
  Haiti: "Haiti",
  Czechia: "República Tcheca",
  "United States": "Estados Unidos",
} as const;
